<?php
	return [
		'rene-sola/homepage' => [
			'title' => 'Homepage',
			'description' => 'Homepage Template',
			'categories' => ['all'],
			'postTypes' => ['page'],
			'content' => '<!-- wp:acf/fr-page-builder {"name":"acf/fr-page-builder","align":"","mode":"preview"} --><!-- wp:acf/hero {"name":"acf/hero","data":{"field_hero_type":"front","field_hero_content":"\u003ch1\u003eHome Hero\u003c/h1\u003e\r\nStart Editing Here","field_hero_image":"","field_hero_image-caption":"","field_hero_buttons":{"63c5c00f86880":{"field_hero_buttons_label":"CTA Button 1","field_hero_buttons_style":"primary dark","field_hero_buttons_cta_type":"externa_url","field_hero_buttons_externa_url":"https://google.com","field_hero_buttons_new_tab":"1"},"63c5c01f86881":{"field_hero_buttons_label":"CTA Button 2","field_hero_buttons_style":"secondary dark","field_hero_buttons_cta_type":"externa_url","field_hero_buttons_externa_url":"https://google.com","field_hero_buttons_new_tab":"1"},"63c5c03186882":{"field_hero_buttons_label":"CTA Button 3","field_hero_buttons_style":"secondary dark","field_hero_buttons_cta_type":"externa_url","field_hero_buttons_externa_url":"https://google.com","field_hero_buttons_new_tab":"1"}},"field_hero_circles":{"row-0":{"field_hero_circles_style":"filled","field_hero_circles_size":"319","field_hero_circles_position":{"desktop":{"top":"48","right":"","bottom":"","left":"-160","linked":"0","unit":"px"},"tablet":{"top":"","right":"","bottom":"","left":"","linked":"0","unit":"px"},"mobile":{"top":"","right":"","bottom":"","left":"","linked":"0","unit":"px"}}},"row-1":{"field_hero_circles_style":"outline","field_hero_circles_size":"249","field_hero_circles_position":{"desktop":{"top":"","right":"-125","bottom":"-17","left":"","linked":"0","unit":"px"},"tablet":{"top":"","right":"","bottom":"","left":"","linked":"0","unit":"px"},"mobile":{"top":"","right":"","bottom":"","left":"","linked":"0","unit":"px"}}}}},"align":"","mode":"preview"} /--><!-- wp:acf/block-container {"name":"acf/block-container","align":"","mode":"preview"} --><!-- wp:acf/fr-page-builder-module-wysiwyg {"name":"acf/fr-page-builder-module-wysiwyg","align":"","mode":"preview"} /--><!-- /wp:acf/block-container --><!-- /wp:acf/fr-page-builder -->',
		],
	];